"""Initial production schema

Revision ID: 39e4415ed3d4
Revises: 
Create Date: 2026-06-29 17:02:56.493641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e4415ed3d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.add_column('properties', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('portfolio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'portfolios', ['portfolio_id'], ['id'])
    op.create_foreign_key(None, 'properties', 'organizations', ['organization_id'], ['id'])
    op.add_column('tenants', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'organizations', ['organization_id'], ['id'])
    op.add_column('transactions', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'organization_id')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'organization_id')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'portfolio_id')
    op.drop_column('properties', 'organization_id')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
